# Day 12 · NumPy 进阶
## 今日学习目标
- 掌握矩阵乘法与线性代数
- 掌握统计函数与 axis 参数
- 掌握随机数生成与文件读写

## 引入
思考：
`np.array([1,2,3]) * np.array([4,5,6])` 结果是？

答：逐元素乘法 → `[4 10 18]`

那真正的矩阵乘法怎么做？
今天就来彻底搞清楚。

## 第一讲：矩阵乘法与线性代数

### 1.1 逐元素乘法 vs 矩阵乘法

In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("A = ")
print(A)
print("B = ")
print(B)

print("\n逐元素乘法 A * B:")
print(A * B)

print("\n矩阵乘法 np.dot(A, B):")
print(np.dot(A, B))

print("\n矩阵乘法 A @ B:")
print(A @ B)

A = 
[[1 2]
 [3 4]]
B = 
[[5 6]
 [7 8]]

逐元素乘法 A * B:
[[ 5 12]
 [21 32]]

矩阵乘法 np.dot(A, B):
[[19 22]
 [43 50]]

矩阵乘法 A @ B:
[[19 22]
 [43 50]]


> 🔴 易错点：矩阵乘法不满足交换律。
`A @ B` 一般 **≠** `B @ A`。

- `*` ：逐元素乘法，形状要一样
- `np.dot` / `@` ：线性代数矩阵乘法，
  左列 = 右行 才能乘，结果形状是 (左行, 右列)

### 1.2 常用线性代数函数

In [2]:
import numpy as np
from numpy import linalg

A = np.array([[1, 2],
              [3, 4]])

print("原矩阵:")
print(A)

print("\n转置 .T:")
print(A.T)

print("\n行列式 det:")
print(linalg.det(A))

print("\n逆矩阵 inv:")
print(linalg.inv(A))

print("\n特征值:")
eigenvalues, eigenvectors = linalg.eig(A)
print(eigenvalues)
print("特征向量:")
print(eigenvectors)

原矩阵:
[[1 2]
 [3 4]]

转置 .T:
[[1 3]
 [2 4]]

行列式 det:
-2.0000000000000004

逆矩阵 inv:
[[-2.   1. ]
 [ 1.5 -0.5]]

特征值:
[-0.37228132  5.37228132]
特征向量:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### ✏️ 练习 1

In [ ]:
import numpy as np

# 创建两个 3x3 矩阵,
# 分别计算逐元素乘法和矩阵乘法

# 学员代码区
pass

In [3]:
# 参考答案
import numpy as np

C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
D = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("C = ")
print(C)
print("D = ")
print(D)

print("\n逐元素乘法 C * D:")
print(C * D)

print("\n矩阵乘法 C @ D:")
print(C @ D)

C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
D = 
[[9 8 7]
 [6 5 4]
 [3 2 1]]

逐元素乘法 C * D:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

矩阵乘法 C @ D:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
import numpy as np
from numpy import linalg

# 计算 2x2 矩阵的行列式和逆矩阵

# 学员代码区
pass

In [4]:
# 参考答案
import numpy as np
from numpy import linalg

M = np.array([[2, 1],
              [5, 3]])

print("M = ")
print(M)

print("\n行列式 det(M):")
print(linalg.det(M))

print("\n逆矩阵 inv(M):")
print(linalg.inv(M))

M = 
[[2 1]
 [5 3]]

行列式 det(M):
1.0

逆矩阵 inv(M):
[[ 3. -1.]
 [-5.  2.]]


## 第二讲：统计函数与 axis

### 2.1 聚合函数

In [5]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("arr = ")
print(arr)

print("\nsum   = ", arr.sum())
print("mean  = ", arr.mean())
print("std   = ", round(arr.std(), 4))
print("max   = ", arr.max())
print("min   = ", arr.min())
print("argmax= ", arr.argmax())

arr = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum   =  45
mean  =  5.0
std   =  2.582
max   =  9
min   =  1
argmax=  8


### 2.2 axis 参数

In [6]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("arr = ")
print(arr)

# axis=0 : 跨行 -> 剩列
print("\naxis=0 (跨行 -> 剩列):")
print(arr.sum(axis=0))

# axis=1 : 跨列 -> 剩行
print("\naxis=1 (跨列 -> 剩行):")
print(arr.sum(axis=1))

arr = 
[[1 2 3]
 [4 5 6]]

axis=0 (跨行 -> 剩列):
[5 7 9]

axis=1 (跨列 -> 剩行):
[ 6 15]


> 🔴 易错点：`axis=0` 不是“对第 0 轴操作”，
而是“沿第 0 轴方向操作”。

- 二维数组：axis=0 是**跨行**（左右列方向消掉）
- 二维数组：axis=1 是**跨列**（上下行方向消掉）

记忆口诀：**axis 指出的是“被吃掉”的维度**。

### 2.3 随机数生成

In [7]:
import numpy as np

np.random.seed(0)

print("均匀分布 rand(2,3):")
print(np.random.rand(2, 3))

print("\n标准正态 randn(2,3):")
print(np.random.randn(2, 3))

print("\n指定正态 normal(loc=50, scale=10):")
print(np.random.normal(50, 10, size=5))

print("\n整数 randint(1, 7, size=6):")
print(np.random.randint(1, 7, size=6))

均匀分布 rand(2,3):
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]

标准正态 randn(2,3):
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]

指定正态 normal(loc=50, scale=10):
[56.43656703 48.74562312 53.36772476 49.12740043 61.53163406]

整数 randint(1, 7, size=6):
[5 6 1 4 4 1]


### ✏️ 练习 2

In [ ]:
import numpy as np

# 创建 5x4 成绩矩阵,
# 计算每人平均分(axis=1) 和 每科平均分(axis=0)

# 学员代码区
pass

In [8]:
# 参考答案
import numpy as np

np.random.seed(0)
scores = np.random.randint(60, 100, size=(5, 4))

print("成绩矩阵 5x4:")
print(scores)

print("\n每人平均分 (axis=1):")
print(scores.mean(axis=1))

print("\n每科平均分 (axis=0):")
print(scores.mean(axis=0))

成绩矩阵 5x4:
[[88 92 79 95]
 [76 85 90 68]
 [91 87 72 83]
 [65 78 84 71]
 [93 96 88 77]]

每人平均分 (axis=1):
[88.5  79.75 83.25 74.5  88.5 ]

每科平均分 (axis=0):
[82.6 87.6 82.6 78.8]


In [ ]:
import numpy as np

# 生成 1000 个 N(50, 10) 随机数,
# 计算实际均值和标准差

# 学员代码区
pass

In [9]:
# 参考答案
import numpy as np

np.random.seed(42)
data = np.random.normal(loc=50, scale=10, size=1000)

print("前 10 个样本:")
print(np.round(data[:10], 2))

print(f"\n实际均值: {data.mean():.2f} (理论值 50)")
print(f"实际标准差: {data.std():.2f} (理论值 10)")

前 10 个样本:
[56.44 48.75 53.37 49.13 61.53 50.95 47.67 59.27 52.51 50.69]

实际均值: 49.87 (理论值 50)
实际标准差: 10.23 (理论值 10)


## 第三讲：文件读写

### 3.1 二进制格式 save / load

In [10]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("原数组:")
print(a)

np.save("_demo.npy", a)
print("\n保存到 _demo.npy ...")

b = np.load("_demo.npy")
print("从 _demo.npy 加载:")
print(b)

原数组:
[[1 2 3]
 [4 5 6]]

保存到 _demo.npy ...
从 _demo.npy 加载:
[[1 2 3]
 [4 5 6]]


### 3.2 文本格式 savetxt / loadtxt

In [11]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 保存为 CSV (逗号分隔)
np.savetxt("data.csv", arr, delimiter=",")
print("保存到 data.csv ...")

# 加载 CSV
loaded = np.loadtxt("data.csv", delimiter=",")
print("从 data.csv 加载:")
print(loaded)

# skiprows=1 跳过表头行
print("\n跳过第 1 行 (skiprows=1):")
skip = np.loadtxt("data.csv", delimiter=",",
                  skiprows=1)
print(skip)

保存到 data.csv ...
从 data.csv 加载:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]

跳过第 1 行 (skiprows=1):
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


> 🔴 易错点：读取中文 CSV 要指定
`encoding='utf-8'`，否则会报编码错误。

- `.npy` ：二进制,快且保留类型,只给 NumPy 用
- `.csv / .txt` ：文本,人可读,通用性强

### ✏️ 练习 3

In [ ]:
import numpy as np

# 创建随机矩阵,
# 保存为 .npy 和 .csv, 再加载验证

# 学员代码区
pass

In [12]:
# 参考答案
import numpy as np

mat = np.array([[10, 20],
                [30, 40]])

print("原矩阵:")
print(mat)

np.save("_ex3.npy", mat)
np.savetxt("_ex3.csv", mat, delimiter=",")

print("\n从 .npy 加载:")
print(np.load("_ex3.npy"))

print("\n从 .csv 加载:")
print(np.loadtxt("_ex3.csv", delimiter=","))

原矩阵:
[[10 20]
 [30 40]]

从 .npy 加载:
[[10 20]
 [30 40]]

从 .csv 加载:
[[10. 20.]
 [30. 40.]]


In [ ]:
import numpy as np

# 用 loadtxt 读取含表头的 CSV 文件
# (跳过第 1 行), 计算每列均值

# 学员代码区
pass

In [13]:
# 参考答案
import numpy as np

# 先写一个带表头的 CSV
header = "col1,col2,col3"
np.savetxt("_header.csv",
           np.array([[1,2,3],[4,5,6],[7,8,9]]),
           delimiter=",", header=header)

# 跳过第 1 行再读取
data = np.loadtxt("_header.csv", delimiter=",",
                  skiprows=1)

print("读取的数据:")
print(data)

print("\n每列均值 (axis=0):")
print(data.mean(axis=0))

读取的数据:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

每列均值 (axis=0):
[4. 5. 6.]


## 总结

| 主题 | 关键函数 |
|---|---|
| 逐元素乘法 | `A * B` |
| 矩阵乘法 | `A @ B` 或 `np.dot(A, B)` |
| 转置 | `A.T` |
| 行列式 | `linalg.det(A)` |
| 逆矩阵 | `linalg.inv(A)` |
| 特征值/向量 | `linalg.eig(A)` |
| 聚合函数 | `sum / mean / std / max / min` |
| axis | `axis=0` 跨行剩列，`axis=1` 跨列剩行 |
| 随机数 | `rand / randn / normal / randint` |
| 种子 | `np.random.seed(n)` |
| 二进制 | `np.save / np.load` (`.npy`) |
| 文本 | `np.savetxt / np.loadtxt` (`.csv`)

## ⭐ 挑战题

In [ ]:
import numpy as np

# 蒙特卡罗模拟：掷骰子 10000 次,
# 统计各点数 (1~6) 出现的频率

# 学员代码区
pass

In [14]:
# 参考答案
import numpy as np

np.random.seed(123)
rolls = np.random.randint(1, 7, size=10000)

print("模拟掷骰子 10000 次:")
for i in range(1, 7):
    count = (rolls == i).sum()
    freq = count / len(rolls)
    print(f"  点数 {i}: {count} 次, 频率 {freq:.4f}")

print(f"\n理论频率: {1/6:.4f} (1/6)")

模拟掷骰子 10000 次:
  点数 1: 1698 次, 频率 0.1698
  点数 2: 1661 次, 频率 0.1661
  点数 3: 1680 次, 频率 0.1680
  点数 4: 1672 次, 频率 0.1672
  点数 5: 1615 次, 频率 0.1615
  点数 6: 1674 次, 频率 0.1674

理论频率: 0.1667 (1/6)
