# Day 11 · NumPy 基础(数组/广播/向量化)

> **前置**: Day01-10 已掌握 Python 核心(变量/容器/函数/OOP/文件/异常)
> **关键问题**: Python 原生列表做百万次数值运算有多慢?NumPy 如何用 C 底层 + 向量化让数值计算快 10-100 倍?

**引入:列表是"杂货铺",数组是"集装箱"**

抽问上节: 列表 `a = [1, 2, 3]`,`a * 2` 结果是什么?(`[1, 2, 3, 1, 2, 3]`,重复不是逐元素乘)。再问: 列表每个元素都要存类型信息,逐个解包 
—— 慢。NumPy 数组是**同类型数据**的连续内存块,底层 C 实现,省掉类型检查开销。同样的数学运算,**换个写法快两个数量级**。


**1. `np.array` 创建 + `dtype` / `shape` / `ndim`**

口诀:**列表是"杂货铺",数组是"集装箱"** —— 同一种货,紧密排列。`dtype` 是数据类型,所有元素共享,混合类型会**强制统一**;`shape` 是形状,元组形式,如 
`(3, 2)` 即 3 行 2 列;`ndim` 是维度数。


In [ ]:
import numpy as np

# 从列表创建
a = np.array([1, 2, 3, 4, 5])
print(a)                        # [1 2 3 4 5]
print(a.dtype)                  # int64,所有元素共享
print(a.shape)                  # (5,),一维,长度 5
print(a.ndim)                   # 1

# 二维数组
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b.shape)                  # (3, 2)
print(b.ndim)                   # 2

# dtype 隐式转换:混合 int+float → 统一 float
print(np.array([1, 2.5, 3]).dtype)  # float64

**✏️ 练一练 ⭐**

用 `np.arange` 创建 0-9 的数组,`reshape` 为 3x3,打印 `shape`、`dtype`、`ndim`。

In [ ]:
# ======================
# 学员代码区
# ======================


In [ ]:
# 参考答案
import numpy as np

a = np.arange(10).reshape(3, 3)  # 注意:0-9 共 10 个
# 严格 3x3 用 arange(9)
a = np.arange(9).reshape(3, 3)
print(a.shape)                  # (3, 3)
print(a.dtype)                  # int64
print(a.ndim)                   # 2

**2. 常用创建函数**

形状参数必须传**元组**,第一个常见 `TypeError`:`np.zeros((2, 3))` 不是 `np.zeros(2, 3)`。

In [ ]:
import numpy as np

print(np.zeros((2, 3)))             # 2x3 全 0
print(np.ones((3, 2)))              # 3x2 全 1
print(np.arange(0, 10, 2))          # [0 2 4 6 8]
print(np.linspace(0, 1, 5))         # [0.  0.25 0.5  0.75 1. ]
print(np.random.rand(3))            # 3 个 [0,1) 随机数

**✏️ 练一练 ⭐⭐**

创建一个 4x4 的全 1 整数数组,和一个长度为 5 的 `linspace`(0 到 10),分别打印。

In [ ]:
# ======================
# 学员代码区
# ======================


In [ ]:
# 参考答案
import numpy as np

a = np.ones((4, 4), dtype=int)
print(a)
b = np.linspace(0, 10, 5)
print(b)                        # [ 0.   2.5  5.   7.5 10. ]

**3. 向量化 + 广播(broadcasting)**

向量化:把"逐个处理"变成"整批处理",底层 C 循环替你跑。广播规则:**从最后一个维度开始对齐,要么相等,要么其中一方是 1,要么一方缺失**。

In [ ]:
import numpy as np

# 向量化(告别 for)
arr = np.arange(5)
result = arr ** 2 + 1               # 逐元素,无需循环
print(result)                       # [ 1  2  5 10 17]

# 广播:小数组被"拉伸"满到大数组形状
a = np.array([[1, 2, 3],
              [4, 5, 6]])           # shape (2, 3)
b = np.array([10, 20, 30])          # shape (3,)
print(a + b)                        # b 被放大到 (2, 3)
# [[11 22 33]
#  [14 25 36]]

**✏️ 练一练 ⭐⭐**

创建一个 shape `(3, 1)` 的数组 `[[1], [2], [3]]` 和一个 shape `(2,)` 的数组 `[10, 20]`,用广播相加,打印结果和结果的 shape。

In [ ]:
# ======================
# 学员代码区
# ======================


In [ ]:
# 参考答案
import numpy as np

a = np.array([[1], [2], [3]])   # shape (3, 1)
b = np.array([10, 20])          # shape (2,)
print(a + b)                    # shape (3, 2)
# [[11 21]
#  [12 22]
#  [13 23]]
print((a + b).shape)            # (3, 2)

**4. 索引 / 切片 / 布尔索引**

NumPy 切片比 list 更强大:`,` 分隔维度;`:` 表示"所有";**布尔索引**直接传条件 —— `arr[arr > 5]` 返回所有大于 5 的元素,无需手写 if。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[0])                         # [1 2 3] 第 0 行
print(a[:, 1])                      # [2 5 8] 第 1 列
print(a[0:2, 1:3])                  # [[2 3] [5 6]] 子矩阵
print(a[a > 5])                     # [6 7 8 9] 布尔索引

**✏️ 练一练 ⭐⭐⭐**

创建一个 4x4 数组(1-16),切片取右下角 2x2 子矩阵,再用布尔索引取所有偶数。

In [ ]:
# ======================
# 学员代码区
# ======================


In [ ]:
# 参考答案
import numpy as np

a = np.arange(1, 17).reshape(4, 4)
sub = a[2:4, 2:4]               # 右下角 2x2
print(sub)                      # [[11 12] [15 16]]
evens = a[a % 2 == 0]
print(evens)                    # [ 2  4  6  8 10 12 14 16]

**5. `reshape` + 常用函数**

`reshape` 返回**视图**(共享内存),修改会影响原数组;需要独立副本用 `.copy()`。常用数学函数都是**逐元素**运算,和向量化一样快。

In [ ]:
import numpy as np

a = np.arange(12)
b = a.reshape(3, 4)                # 3 行 4 列
c = a.reshape(2, -1)               # -1 自动算 → (2, 6)
print(b)

# 视图验证
b[0, 0] = 99
print(a[0])                         # 99(原数组也变了)

# 逐元素函数
x = np.array([1, 4, 9, 16])
print(np.sqrt(x))                   # [1. 2. 3. 4.]
print(np.sum(x), np.mean(x))        # 30 7.5

**✏️ 练一练 ⭐⭐⭐⭐**

用广播实现"矩阵每行减去该行最小值"。提示:`arr.min(axis=1, keepdims=True)` 保持维度才能广播。

In [ ]:
# ======================
# 学员代码区
# ======================


In [ ]:
# 参考答案
import numpy as np

arr = np.array([[5, 2, 8],
                [1, 9, 4]])
result = arr - arr.min(axis=1, keepdims=True)
print(result)
# [[3 0 6]
#  [0 8 3]]

**📝 本节试题集**

想更多练习?参见:
- 当堂练:`course/lesson11/in_class/practice01-06.py`(6 道)
- 课后作业:`course/lesson11/homework/task01-03.py`(3 道)

**今日小结**

`np.array` 创建数组;`dtype/shape/ndim` 数组身份证;`arange/zeros/ones/linspace` 
常用工厂;向量化逐元素运算;广播对齐规则;布尔索引条件筛选;`reshape` 返回视图。

| 知识点 | 核心语法 | 一句话 |
|---|---|---|
| 数组创建 | `np.array(list)` | 同类型连续内存 |
| 身份证 | `.dtype` / `.shape` / `.ndim` | 类型/形状/维度 |
| 向量化 | `arr ** 2 + 1` | 整批处理,告别 for |
| 广播 | 小数组"拉伸"大数组 | 从最后维度对齐 |
| 布尔索引 | `arr[arr > 5]` | 条件直接筛选 |

> 🔴 **易错点**:形状漏写元组括号,`np.zeros(2, 3)` 报 `TypeError`;`reshape` 返回视图改后原数组也变;`axis` 方向混淆。