# Day 11 · NumPy 基础

> 🎯 **今日学习目标**
> 1. 理解为什么 NumPy 比 Python 列表快
> 2. 掌握数组创建、属性、索引
> 3. 掌握向量化运算与广播机制

---

## 📖 引入: 同样的 `* 2`, 不同的含义

📖 **概念: Python 列表 vs NumPy 数组**

Python 列表 `* 2` 是**重复**, NumPy 数组 `* 2` 是**逐元素乘**。

In [ ]:
# Python 列表:* 2 表示重复两次
py_list = [1, 2, 3]
print("列表 * 2:", py_list * 2)   # [1, 2, 3, 1, 2, 3]

# NumPy 数组:* 2 表示每个元素乘以 2
import numpy as np
np_arr = np.array([1, 2, 3])
print("数组 * 2:", np_arr * 2)     # [2 4 6]

💡 **为什么要用 NumPy?**

- 列表存的是**对象引用**(每一个元素都是一块内存)
- 数组存的是**同类型的连续内存**, 运算快、内存小

In [ ]:
# 💡 性能对比: 对 100 万个数各自乘以 2
import time

data = list(range(1_000_000))          # 普通列表
start = time.time()
result = [x * 2 for x in data]         # 列表推导
print("列表耗时:", time.time() - start)

arr = np.arange(1_000_000)             # NumPy 数组
start = time.time()
result = arr * 2                       # 向量化运算
print("数组耗时:", time.time() - start)

---

## 第一讲: 数组创建与基本属性

### 1.1 为什么需要 NumPy

📖 **概念: 内存布局差异**

列表: 每个元素是独立的 Python 对象, 互不相关  
数组: 一整块连续内存, 元素类型相同, 寻址一步到位

In [ ]:
# 💡 从列表创建 NumPy 数组
import numpy as np  # 标准导入写法

# 一维数组(向量)
a = np.array([1, 2, 3, 4, 5])
print(a)          # [1 2 3 4 5]
print(type(a))    # <class 'numpy.ndarray'>

# 二维数组(矩阵)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)
# [[1 2 3]
#  [4 5 6]]

### 1.2 dtype / shape / ndim — 数组的"身份证"

📖 **概念: 三大核心属性**

- `dtype`: 元素类型 (如 int64、float64)
- `shape`: 形状 (各行、各列的长度)
- `ndim`: 维度数 (几维数组)

In [ ]:
# 💡 查看数组的"身份证"
a = np.array([1, 2, 3])
print("dtype:", a.dtype)    # int64  ← 所有元素共享同一类型
print("shape:", a.shape)    # (3,)   ← 一维,长度 3
print("ndim:", a.ndim)      # 1      ← 维度数

print("---")

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print("dtype:", b.dtype)    # int64
print("shape:", b.shape)    # (3, 2) ← 3 行 2 列
print("ndim:", b.ndim)      # 2

🔴 **易错点: 列表可以混合类型, 数组不行**

In [ ]:
# 🔴 数组会自动统一类型(这里是向上转型为字符串)
mixed = np.array([1, "hello", 3.14])
print(mixed)         # ['1' 'hello' '3.14']
print(mixed.dtype)   # <U32 (Unicode 字符串)

### 1.3 常用创建函数

📖 **概念: 一键造数组**

| 函数 | 用途 |
|---|---|
| `zeros(n)` | 全 0 |
| `ones(n)` | 全 1 |
| `arange(start, stop, step)` | 等差序列 |
| `linspace(start, stop, num)` | 等间隔 |
| `rand(...)` | 随机数 |

In [ ]:
# 💡 zeros / ones
print(np.zeros(5))       # [0. 0. 0. 0. 0.]
print(np.ones((2, 3)))   # 2 行 3 列的全 1 矩阵

# 💡 arange: 类似 range, 但返回数组
print(np.arange(0, 10, 2))   # [0 2 4 6 8]

# 💡 linspace: 在 0~1 之间均匀取 5 个点
print(np.linspace(0, 1, 5))  # [0.   0.25 0.5  0.75 1.  ]

# 💡 rand: 0~1 均匀分布的随机数
print(np.random.rand(3))     # 如 [0.23 0.87 0.41]

---

## ✏️ 练习 1

#### 练习 1-1

创建一个形状为 `(3, 4)` 的全 1 整数数组, 并打印它的
`dtype`、`shape`、`ndim`。

In [ ]:
# ============
# TODO: 在此编写你的代码
# ============
pass

In [ ]:
# 参考答案
import numpy as np

arr = np.ones((3, 4), dtype=int)   # 指定 dtype 为整数
print("数组:\n", arr)
print("dtype:", arr.dtype)
print("shape:", arr.shape)
print("ndim:", arr.ndim)

#### 练习 1-2

用 `linspace` 生成 `[0, 2π]` 之间等距的 100 个点, 计算
这些点的正弦值 (`np.sin`), 并打印前 5 个。

In [ ]:
# ============
# TODO: 在此编写你的代码
# ============
pass

In [ ]:
# 参考答案
import numpy as np

x = np.linspace(0, 2 * np.pi, 100)   # 100 个等距点
y = np.sin(x)                         # 逐元素求正弦
print("前 5 个 x:", x[:5])
print("前 5 个 y:", y[:5])

---

## 第二讲: 向量化运算与广播

### 2.1 向量化: 告别 for 循环

📖 **概念: 一条语句代替循环**

对整个数组做运算, 不用写 `for` — 这就是向量化。

In [ ]:
# 💡 逐元素加减乘除
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)   # [11 22 33]
print(a - b)   # [-9 -18 -27]
print(a * b)   # [10 40 90]
print(b / a)   # [10.  10.  10.]

In [ ]:
# 💡 标量直接参与运算(同样逐元素)
print(a + 100)   # [101 102 103]
print(a ** 2)    # [1 4 9]

🔴 **易错点: `*` 是逐元素乘, 不是矩阵乘法**

In [ ]:
# 🔴 逐元素乘 与 矩阵乘 的区别
a = np.array([1, 2])
b = np.array([3, 4])

print("逐元素乘 a*b:", a * b)          # [3 8]
print("矩阵乘 a@b:", a @ b)             # 11 (=1*3+2*4)
print("矩阵乘 np.dot:", np.dot(a, b))   # 11

### 2.2 广播 Broadcasting 规则

📖 **概念: 自动对齐维度**

两个数组形状不同, NumPy 会自动把小数组"拉伸"  
到和大数组一样大再运算 — 这叫广播。

In [ ]:
# 💡 广播: (2, 3) + (3,) → (2, 3)
a = np.array([[1, 2, 3],
              [4, 5, 6]])     # shape (2, 3)
b = np.array([10, 20, 30])    # shape (3,)

print(a + b)  # b 被"拉伸"成 (2, 3) 再相加
# [[11 22 33]
#  [14 25 36]]

In [ ]:
# 💡 广播: (3, 1) + (1, 3) → (3, 3)
col = np.array([[10],
                [20],
                [30]])        # shape (3, 1)
row = np.array([[1, 2, 3]])    # shape (1, 3)

print(col + row)
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]

🔴 **易错点: 能广播的前提是对应维度长度相等或为 1**

In [ ]:
# 🔴 形状不匹配, 会报错
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)
c = np.array([10, 20])      # shape (2,) ← 无法广播

try:
    print(a + c)
except ValueError as e:
    print("报错:", e)

### 2.3 索引与切片

📖 **概念: 取行、取列、取子矩阵、条件筛选**

In [ ]:
# 💡 基础索引与切片
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[0])        # 第 0 行 → [1 2 3]
print(a[0, 1])     # 第 0 行 第 1 列 → 2
print(a[:, 1])     # 所有行的第 1 列 → [2 5 8]
print(a[0:2, 1:3]) # 子矩阵(行 0~1, 列 1~2)
# [[2 3]
#  [5 6]]

In [ ]:
# 💡 布尔索引: 根据条件筛选元素
a = np.array([5, 15, 25, 35, 45])
mask = a > 20            # 生成布尔数组
print(mask)              # [False False  True  True  True]
print(a[mask])           # [25 35 45]
print(a[a % 2 == 1])     # 取所有奇数

---

## ✏️ 练习 2

#### 练习 2-1

创建数组 `a = np.arange(1, 7)`, 用广播把它变成
`[[1,2,3],[4,5,6]]`, 再加 `[10,20,30]`, 打印结果。

In [ ]:
# ============
# TODO: 在此编写你的代码
# ============
pass

In [ ]:
# 参考答案
import numpy as np

a = np.arange(1, 7)                # [1 2 3 4 5 6]
b = a.reshape(2, 3)                # 变成 (2, 3)
result = b + np.array([10, 20, 30])  # 广播相加
print(result)
# [[11 22 33]
#  [14 25 36]]

#### 练习 2-2

创建一个 5×5 的随机整数数组 (0~99), 打印其中
所有**大于 50 的偶数**。

In [ ]:
# ============
# TODO: 在此编写你的代码
# ============
pass

In [ ]:
# 参考答案
import numpy as np

np.random.seed(0)  # 固定随机种子, 便于复现
arr = np.random.randint(0, 100, size=(5, 5))
print("原数组:\n", arr)

mask = (arr > 50) & (arr % 2 == 0)   # 同时满足两个条件
print("大于 50 的偶数:", arr[mask])

---

## 第三讲: reshape 与常用函数

### 3.1 reshape (视图 vs 副本)

📖 **概念: 不改变数据, 只改变"看数据的视角"**

reshape 默认返回**视图**(共享内存), 改视图会影响原数组。

In [ ]:
# 💡 reshape 的基础用法
a = np.arange(12)              # 0~11
b = a.reshape(3, 4)            # 变成 3 行 4 列
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# 用 -1 让 NumPy 自动推算这一维的长度
c = a.reshape(2, -1)           # 2 行, 自动算列数
print("shape:", c.shape)       # (2, 6)

🔴 **易错点: 视图共享内存**

In [ ]:
# 🔴 修改视图会影响原数组
a = np.arange(6)
b = a.reshape(2, 3)            # b 是 a 的视图
b[0, 0] = 999                  # 改视图
print(a)                       # [999   1   2   3   4   5] ← a 也变了!

# 要想独立, 用 .copy()
c = a.reshape(2, 3).copy()
c[0, 0] = 0
print(a)                       # a 不变

### 3.2 常用数学函数

📖 **概念: 逐元素数学函数**

| 函数 | 含义 |
|---|---|
| `np.sqrt` | 开方 |
| `np.exp` | e^x |
| `np.log` | 自然对数 |
| `np.sum` | 求和 |
| `np.mean` | 均值 |

In [ ]:
# 💡 常用数学函数示例
a = np.array([1, 4, 9, 16])

print(np.sqrt(a))    # [1. 2. 3. 4.]
print(np.exp(a[:2])) # [ 2.718  54.598]
print(np.log(a[1:])) # [1.386 2.197 2.773]

# 💡 聚合函数
b = np.array([[1, 2],
              [3, 4]])
print("总和:", np.sum(b))          # 10
print("均值:", np.mean(b))         # 2.5
print("按行求和:", b.sum(axis=1))  # [3 7]
print("按列求和:", b.sum(axis=0))  # [4 6]

---

## ✏️ 练习 3

#### 练习 3

创建数组 `a = np.arange(1, 10)`, 把它 reshape 成
`(3, 3)`, 然后计算:
1. 整体的均值
2. 每行的最大值
3. 每个元素的平方根

In [ ]:
# ============
# TODO: 在此编写你的代码
# ============
pass

In [ ]:
# 参考答案
import numpy as np

a = np.arange(1, 10).reshape(3, 3)
print("矩阵:\n", a)

print("整体均值:", np.mean(a))
print("每行最大值:", a.max(axis=1))
print("每个元素的平方根:\n", np.sqrt(a))

---

## 📖 今日小结

**核心知识点回顾:**

1. NumPy 数组是同类型连续内存, 比列表快
2. `dtype`、`shape`、`ndim` 是数组的三大属性
3. 向量化运算: 不写 for, 对整个数组直接算
4. 广播机制: 小数组自动"拉伸"到大数组再运算
5. reshape 是视图(共享内存), 想独立用 `.copy()`

---

## ⭐ 挑战题: 广播实现矩阵标准化

⭐ **题目: 用广播把矩阵标准化(Z-score)**

标准化公式:

$$z = \frac{x - \mu}{\sigma}$$

其中 μ 是每列的均值, σ 是每列的标准差。

**要求:** 只用 NumPy 广播 + 聚合函数, 不用 for 循环。

In [ ]:
# ============
# TODO: 在此编写你的代码
# ============
pass

In [ ]:
# 参考答案: 广播实现 Z-score 标准化
import numpy as np

np.random.seed(42)                          # 固定种子
data = np.random.randint(0, 100, (5, 3))    # 5 行 3 列
print("原始矩阵:\n", data)

mu = data.mean(axis=0)                      # 每列均值,shape (3,)
sigma = data.std(axis=0)                    # 每列标准差

z = (data - mu) / sigma                     # 广播: (5,3)-(3,) / (3,)
print("标准化后:\n", np.round(z, 2))

# 验证: 标准化后每列均值 ≈ 0, 标准差 ≈ 1
print("列均值:", z.mean(axis=0).round(10))
print("列标准差:", z.std(axis=0).round(10))

---

✅ **学习检查清单**

- [ ] 能说出列表和数组在内存上的区别
- [ ] 会查看 `dtype`、`shape`、`ndim`
- [ ] 能使用 `zeros`/`arange`/`linspace` 创建数组
- [ ] 能解释广播的规则
- [ ] 会用 reshape 和布尔索引
- [ ] 完成了挑战题 Z-score 标准化

🎉 恭喜完成 Day 11 · NumPy 基础!