# Day 11 · NumPy 基础
## 今日学习目标
- 理解为什么 NumPy 比 Python 列表快
- 掌握数组创建、属性、索引
- 掌握向量化运算与广播机制

## 引入
思考: Python 列表 `a = [1, 2, 3]`, `a * 2` 结果是?

答案: `[1, 2, 3, 1, 2, 3]` (列表重复,不是每个元素乘 2)

如果想让每个元素都乘 2,必须用 for 循环或列表推导,
而 NumPy 数组直接写 `a * 2` 即可,简洁又高效。

## 第一讲:数组创建与基本属性

### 1.1 为什么需要 NumPy

In [1]:
import numpy as np

# 从列表创建数组
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


> 🔴 易错点:列表是'杂货铺',可以混放不同类型;
> 数组是'集装箱',所有元素必须是同一类型。
> 混放时 NumPy 会自动向上转换类型。

### 1.2 dtype 与 shape

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print("dtype:", a.dtype)
print("shape:", a.shape)
print("ndim:", a.ndim)

print("---")
# 隐式转换: int + float → float
b = np.array([1, 2, 3.0])
print("int + float →", b.dtype)
print(b)

# 隐式转换: int + str → str
c = np.array([1, 2, "3"])
print("int + str  →", c.dtype)
print(c)

dtype: int64
shape: (5,)
ndim: 1
---
int + float → float64
[1. 2. 3.]
int + str  → <U21
['1' '2' '3']


> 🔴 易错点:dtype 隐式转换。一旦列表里有字符串,
> 所有元素都会被转成字符串,数值运算会报错。
> 写代码时务必保证数据类型一致。

### 1.3 常用创建函数

In [3]:
import numpy as np

# 创建全 0 数组 (2 行 3 列)
z = np.zeros((2, 3))
print("zeros:\n", z)

# 创建全 1 数组 (3 行 2 列)
o = np.ones((3, 2))
print("ones:\n", o)

# arange: 类似 range,左闭右开
a = np.arange(0, 10, 2)
print("arange:\n", a)

# linspace: 均匀分割 (包含终点)
l = np.linspace(0, 1, 5)
print("linspace:\n", l)

# rand: [0, 1) 均匀分布随机数
r = np.random.rand(2, 2)
print("rand:\n", r)

zeros:\n [[0. 0. 0.]\n [0. 0. 0.]]\nones:\n [[1. 1.]\n [1. 1.]\n [1. 1.]]\narange:\n [0 2 4 6 8]\nlinspace:\n [0.   0.25 0.5  0.75 1.  ]\nrand:\n [[0.37454012 0.95071431]\n [0.73199394 0.59865848]]\n

### ✏️ 练习 1-1
用 `np.arange` 创建 0~9 一维数组,reshape 为 3×3,
打印 shape 和 dtype。

In [ ]:
import numpy as np
# 学员代码区
pass

In [4]:
# 参考答案
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)
print("shape:", arr.shape)
print("dtype:", arr.dtype)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape: (3, 3)
dtype: int64


### ✏️ 练习 1-2
用 `np.zeros` 和 `np.ones` 分别创建指定形状数组,
计算元素总数。

In [ ]:
import numpy as np
# 学员代码区
pass

In [5]:
# 参考答案
import numpy as np

z = np.zeros((3, 4))
o = np.ones((2, 3))
print("zeros 元素总数:", z.size)
print("ones  元素总数:", o.size)

zeros 元素总数: 12
ones  元素总数: 6


## 第二讲:向量化运算与广播

### 2.1 向量化:告别 for 循环

In [6]:
import numpy as np

# Python 列表: 必须用 for 循环
lst = [1, 2, 3, 4, 5]
result_list = []
for x in lst:
    result_list.append(x * 2)
print("列表 for 循环:", result_list)

# NumPy 数组: 直接运算(向量化)
arr = np.array([1, 2, 3, 4, 5])
result_arr = arr * 2
print("NumPy 向量化:", result_arr)

print("向量化无需循环,代码更简洁")

列表 for 循环: [2, 4, 6, 8, 10]
NumPy 向量化: [ 2  4  6  8 10]
向量化无需循环,代码更简洁


### 2.2 广播(broadcasting)

In [7]:
import numpy as np

# 广播: (2, 3) + (3,) → (2, 3)
A = np.array([[1, 2, 3],
              [2, 3, 4]])
B = np.array([0, 1, 2])

print("A shape:", A.shape)
print("B shape:", B.shape)
print("A + B =\n", A + B)

A shape: (2, 3)
B shape: (3,)
A + B =
[[1 3 5]
 [3 5 7]]


> 🔴 易错点:广播从最后一个维度对齐。
> 两个数组对应维度长度相等,或其中一个是 1,才能广播。
> 例如 (2, 3) 和 (2, 1) 可以广播,但 (2, 3) 和 (2,) 不行。

### 2.3 索引与切片

In [8]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 取第 1 行 (索引从 0 开始)
print("取第 1 行:", arr[1, :])

# 取第 1 列
print("取第 1 列:", arr[:, 1])

# 取子矩阵 (前两行,前两列)
print("取子矩阵 (左上 2×2):\n", arr[:2, :2])

# 布尔索引: 取出偶数
even = arr[arr % 2 == 0]
print("布尔索引 (取偶数):", even)

取第 1 行: [4 5 6]
取第 1 列: [2 5 8]
取子矩阵(左上 2×2):
[[1 2]
 [4 5]]
布尔索引(取偶数): [2 4 6 8]


### ✏️ 练习 2-1
创建 4×4 数组,切片取右下角 2×2 子矩阵,
再用布尔索引取出所有偶数。

In [ ]:
import numpy as np
# 学员代码区
pass

In [9]:
# 参考答案
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
sub = arr[2:, 2:]
print("右下角 2×2:\n", sub)

even = arr[arr % 2 == 0]
print("偶数:", even)

右下角 2×2:
 [[10 11]
 [14 15]]
偶数: [ 2  4  6  8 10 12 14]


### ✏️ 练习 2-2
用广播实现:矩阵每行减去该行最小值,
注意使用 `keepdims=True`。

In [ ]:
import numpy as np
# 学员代码区
pass

In [10]:
# 参考答案
import numpy as np

arr = np.array([[5, 2, 9],
                [1, 7, 3]])
row_min = arr.min(axis=1, keepdims=True)
result = arr - row_min
print("原矩阵:\n", arr)
print("每行减最小值:\n", result)

原矩阵:
 [[5 2 9]
 [1 7 3]]
每行减最小值:
 [[3 0 7]
 [0 6 4]]


## 第三讲:reshape 与常用函数

### 3.1 reshape

In [11]:
import numpy as np

arr = np.arange(12)
print("原数组:", arr)

# reshape 为 3 行 4 列
b = arr.reshape(3, 4)
print("reshape(3, 4):\n", b)

# -1 表示该维度长度自动推断
c = arr.reshape(2, -1)
print("reshape(2, -1):  # -1 自动推断\n", c)

原数组: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape(3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape(2, -1):  # -1 自动推断
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


> 🔴 易错点:reshape 返回视图(view)不是副本(copy)。
> 修改视图会影响原数组。如需独立副本,请用 `.copy()`。

### 3.2 常用数学函数

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# 逐元素运算
print("sqrt:", np.sqrt(arr))
print("exp: ", np.exp(arr))
print("log: ", np.log(arr))

# 聚合函数
print("sum: ", arr.sum())
print("mean:", arr.mean())

sqrt: [1.         1.41421356 1.73205081 2.        ]
exp:  [  2.71828183   7.3890561   20.08553692  54.59815003]
log:  [0.         0.69314718 1.09861229 1.38629436]
sum:  10
mean: 2.5


### ✏️ 练习 3
用 `np.random.rand` 生成 1000 个随机数,
计算均值、标准差、最大值,
再 reshape 为 25×40 后按行求和。

In [ ]:
import numpy as np
# 学员代码区
pass

In [13]:
# 参考答案
import numpy as np

np.random.seed(42)
data = np.random.rand(1000)
print("均值:", round(data.mean(), 6))
print("标准差:", round(data.std(), 6))
print("最大值:", round(data.max(), 6))

reshaped = data.reshape(25, 40)
row_sums = reshaped.sum(axis=1)
print("按行求和 shape:", row_sums.shape)

均值: 0.498532
标准差: 0.288214
最大值: 0.999847
按行求和 shape: (25,)


## 总结
- 今日易错点回顾:
  1. 数组元素类型一致,混放会隐式转换
  2. 广播从最后一个维度对齐
  3. reshape 返回视图,修改会影响原数组
- 核心函数:`np.array / zeros / ones / arange / linspace`
- 核心运算:向量化、广播、布尔索引

## ⭐ 挑战题
用广播实现矩阵标准化:每个元素减去均值,再除以标准差。
公式: `z = (x - mean) / std`

In [ ]:
import numpy as np
# 学员代码区
pass

In [14]:
# 参考答案
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=float)
mean = arr.mean()
std = arr.std()
z = (arr - mean) / std
print("标准化后:\n", z)
print("均值 ≈ 0.0, 标准差 =", round(z.std(), 2))

标准化后:
 [[-1.41421356 -0.70710678  0.        ]
 [ 0.70710678  1.41421356  2.12132034]]
均值 ≈ 0.0, 标准差 = 1.0
