### Day 12 · NumPy 进阶(线性代数/随机数/统计)

**引入:逐元素乘法 vs 矩阵乘法**

抽问上节:`np.array([1,2,3]) * np.array([4,5,6])` 结果是什么?(`[4,10,18]`,逐元素相乘)。今天学**矩阵乘法(点积)**,写法完全不同,意义也不同。线性代数是数据科学的数学底座。

#### 导入 NumPy

标准写法 `import numpy as np`,所有教材/项目通用。

In [ ]:
import numpy as np


#### 逐元素乘法 vs 矩阵乘法

[痛点] 初学者混淆 `*` 和 `@`,以为 `*` 就是矩阵乘法,结果完全错误。
[类比] `*` 是"对位握手"(逐元素),`@` 是"行乘列"(线性代数)。
[解释] `*` 逐元素相乘,要求形状相同或可广播。`np.dot(a,b)` 或 `a @ b` 是矩阵乘法,要求 a 的列数 = b 的行数。口诀:**`*` 是对位乘,`@` 是行乘列**。

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

# 逐元素乘法(对位乘)
print(a * b)
# [[ 5 12]
#  [21 32]]

# 矩阵乘法(行乘列)
print(np.dot(a, b))
# [[19 22]    ← 1*5+2*7=19, 1*6+2*8=22
#  [43 50]]   ← 3*5+4*7=43, 3*6+4*8=50

# @ 运算符(Python 3.5+,推荐写法)
print(a @ b)  # 和 np.dot(a, b) 等价


# --- 执行过程 ---

① 第2行: 创建 2x2 矩阵 a

② 第4行: 创建 2x2 矩阵 b

③ 第7行: `a * b` 逐元素相乘,1*5=5, 2*6=12, ...

④ 第11行: `np.dot(a,b)` 矩阵乘法,行乘列

⑤ 第15行: `a @ b` 与 np.dot 等价,推荐写法

**逐行解剖**

- `a * b`:逐元素乘法,对应位置相乘
- `np.dot(a,b)`:矩阵乘法,行乘列求和
- `a @ b`:Python 3.5+ 推荐的矩阵乘法运算符
- 矩阵乘法**不满足交换律**,`A @ B` ≠ `B @ A`

**练习**

创建两个 2x2 矩阵 `A=[[1,2],[3,4]]` 和 `B=[[2,0],[1,2]]`,分别计算逐元素乘法和矩阵乘法,验证结果不同。

> 问自己:
> - 这道题要用到今天学的哪个知识点? (* vs @)
> - 如果运行报错,检查什么? (矩阵形状是否匹配)

In [ ]:
import numpy as np

# 学员代码区
pass


In [ ]:
import numpy as np

# 参考答案
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])
print(A * B)          # 逐元素: [[2 0], [3 8]]
print(A @ B)          # 矩阵乘: [[4 4], [10 8]]


#### 转置与逆矩阵

[痛点] 线性代数运算需要转置、求逆,手写算法太复杂。
[类比] 转置像"把矩阵沿对角线翻转",逆矩阵像"数的倒数"——乘以逆矩阵等于单位矩阵。
[解释] `a.T` 转置,`np.linalg.det(a)` 行列式,`np.linalg.inv(a)` 逆矩阵。验证:`A @ inv(A) = I`(单位矩阵)。

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

# 转置:行变列,列变行
print(a.T)
# [[1 3]
#  [2 4]]

# 行列式:只有方阵才有行列式
print(np.linalg.det(a))  # -2.0

# 逆矩阵:A @ inv(A) = I
inv_a = np.linalg.inv(a)
print(inv_a)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 验证:A @ inv(A) 应该等于单位矩阵
print(np.round(a @ inv_a, 5))  # [[1. 0.], [0. 1.]]


# --- 执行过程 ---

① 第2行: 创建 2x2 矩阵 a

② 第5行: `a.T` 转置,行变列

② 第9行: `np.linalg.det(a)` 计算行列式 = 1*4 - 2*3 = -2

③ 第12行: `np.linalg.inv(a)` 求逆矩阵

④ 第17行: 验证 `a @ inv_a` 等于单位矩阵

**逐行解剖**

- `a.T`:转置,沿对角线翻转
- `np.linalg.det(a)`:行列式,只有方阵才有
- `np.linalg.inv(a)`:逆矩阵,要求行列式不为 0
- `np.round(..., 5)`:浮点数精度问题,四舍五入验证

**练习**

创建矩阵 `[[2,1],[5,3]]`,计算它的逆矩阵,并验证 `A @ inv(A)` 等于单位矩阵。

> 问自己:
> - 这道题要用到今天学的哪个知识点? (np.linalg.inv)
> - 如果运行报错,检查什么? (行列式是否为 0,0 则不可逆)

In [ ]:
import numpy as np

# 学员代码区
pass


In [ ]:
import numpy as np

# 参考答案
A = np.array([[2, 1],
              [5, 3]])
inv_A = np.linalg.inv(A)
print(inv_A)          # [[ 3. -1.], [-5.  2.]]
print(np.round(A @ inv_A, 5))  # [[1. 0.], [0. 1.]]


#### 统计函数 sum / mean / std / argmax

[痛点] 需要计算数组的统计量,手写循环累加太繁琐。
[类比] 统计函数像"数据体检"——快速了解数据的分布特征。
[解释] `sum` 求和,`mean` 平均,`std` 标准差,`argmax` 最大值的扁平化索引。不指定 axis 时对整个数组计算。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 对整个数组计算
print(a.sum())        # 21,所有元素求和
print(a.mean())       # 3.5,所有元素平均
print(a.std())        # 1.707...,标准差
print(a.max())        # 6,最大值
print(a.min())        # 1,最小值
print(a.argmax())     # 5,最大值的扁平化索引(拉平后位置)


# --- 执行过程 ---

① 第2行: 创建 2x3 矩阵

② 第5行: `a.sum()` 求和 = 1+2+3+4+5+6 = 21

③ 第6行: `a.mean()` 平均 = 21/6 = 3.5

④ 第7行: `a.std()` 标准差

⑤ 第10行: `a.argmax()` 返回拉平后最大值的索引

**逐行解剖**

- `sum/mean/std`:聚合函数,返回标量
- `argmax`:返回**扁平化索引**,多维数组拉平后的位置
- 两种写法等价:`np.sum(a)` 和 `a.sum()`

**练习**

创建数组 `[3, 7, 1, 9, 4]`,计算总和、平均值、标准差和最大值。

> 问自己:
> - 这道题要用到今天学的哪个知识点? (统计函数)
> - 如果运行报错,检查什么? (数组是否正确创建)

In [ ]:
import numpy as np

# 学员代码区
pass


In [ ]:
import numpy as np

# 参考答案
a = np.array([3, 7, 1, 9, 4])
print(a.sum())        # 24
print(a.mean())       # 4.8
print(a.std())        # 2.946...
print(a.max())        # 9


#### axis 参数 沿哪个轴聚合

[痛点] 二维数组需要按行或按列聚合,不知道 axis 该设 0 还是 1。
[类比] axis=0 是"跨行"(压扁行,剩列),axis=1 是"跨列"(压扁列,剩行)。
[解释] `axis=0` 沿行方向操作,结果是每列一个值。`axis=1` 沿列方向操作,结果是每行一个值。记忆口诀:**axis=0 跨行 → 剩列**。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

# axis=0:沿行方向(跨行计算),结果是每列一个值
print(a.sum(axis=0))  # [5 7 9]  ← 每列求和

# axis=1:沿列方向(跨列计算),结果是每行一个值
print(a.sum(axis=1))  # [ 6 15]  ← 每行求和

# 同理适用于 mean/std 等
print(a.mean(axis=0)) # [2.5 3.5 4.5]
print(a.mean(axis=1)) # [2. 5.]


# --- 执行过程 ---

① 第2行: 创建 2x3 矩阵

② 第5行: `a.sum(axis=0)` 跨行求和,每列一个值 [1+4, 2+5, 3+6]

③ 第8行: `a.sum(axis=1)` 跨列求和,每行一个值 [1+2+3, 4+5+6]

④ 第11行: `a.mean(axis=0)` 每列平均

⑤ 第12行: `a.mean(axis=1)` 每行平均

**逐行解剖**

- `axis=0`:沿第 0 轴(行)方向操作,跨行计算,结果长度 = 列数
- `axis=1`:沿第 1 轴(列)方向操作,跨列计算,结果长度 = 行数
- 口诀:axis=0 跨行剩列,axis=1 跨列剩行

**练习**

创建 3x4 成绩矩阵(3 个学生,4 科成绩),计算每个学生的平均分(axis=1)和每科的平均分(axis=0)。

> 问自己:
> - 这道题要用到今天学的哪个知识点? (axis 参数)
> - 如果运行报错,检查什么? (axis 值是否正确,0 跨行 1 跨列)

In [ ]:
import numpy as np

# 学员代码区
pass


In [ ]:
import numpy as np

# 参考答案
scores = np.array([[80, 90, 85, 88],
                   [70, 75, 80, 72],
                   [90, 95, 92, 98]])
print(scores.mean(axis=1))  # 每个学生的平均分
print(scores.mean(axis=0))  # 每科的平均分


#### 随机数生成 seed / normal / randint

[痛点] 机器学习实验需要可复现的随机数,不设 seed 每次结果不同。
[类比] seed 是"随机数种子"——同样的种子长出同样的随机数序列。
[解释] `np.random.seed(42)` 设种子,`np.random.rand(m,n)` 均匀分布 [0,1),`np.random.randn(m,n)` 标准正态分布,`np.random.normal(mean,std,size)` 指定均值标准差,`np.random.randint(low,high,size)` 均匀整数。

In [ ]:
import numpy as np

# 设置随机种子,保证可复现
np.random.seed(42)

# 均匀分布 [0,1),3 行 2 列
print(np.random.rand(3, 2))

# 标准正态分布 N(0,1),5 个
print(np.random.randn(5))

# 指定均值和标准差的正态分布 N(10,4)
print(np.random.normal(10, 2, 5))

# 均匀整数 [1,7),10 个骰子点数
print(np.random.randint(1, 7, 10))


# --- 执行过程 ---

① 第2行: `np.random.seed(42)` 设种子,保证每次运行结果相同

② 第5行: `np.random.rand(3,2)` 生成 3x2 均匀分布随机数

③ 第8行: `np.random.randn(5)` 生成 5 个标准正态分布随机数

④ 第11行: `np.random.normal(10,2,5)` 生成 5 个 N(10,4) 随机数

⑤ 第14行: `np.random.randint(1,7,10)` 生成 10 个 1-6 的整数

**逐行解剖**

- `np.random.seed(42)`:设种子,42 是惯例(来自《银河系漫游指南》)
- `np.random.rand(m,n)`:均匀分布 [0,1)
- `np.random.randn(m,n)`:标准正态分布 N(0,1)
- `np.random.normal(mean,std,size)`:指定均值和标准差
- `np.random.randint(low,high,size)`:均匀整数,不含 high

**练习**

设种子为 0,生成 1000 个 N(50, 10) 的正态分布随机数,计算实际均值和标准差,验证接近理论值。

> 问自己:
> - 这道题要用到今天学的哪个知识点? (np.random.normal + seed)
> - 如果运行报错,检查什么? (normal 的参数顺序:均值,标准差,数量)

In [ ]:
import numpy as np

# 学员代码区
pass


In [ ]:
import numpy as np

# 参考答案
np.random.seed(0)
data = np.random.normal(50, 10, 1000)
print(data.mean())  # 接近 50
print(data.std())   # 接近 10


#### 文件读写 save / load / savetxt / loadtxt

[痛点] 数组需要保存到文件,但 pickle 格式不通用,CSV 格式丢失形状信息。
[类比] .npy 是"NumPy 专用压缩包",.npz 是"多个数组的压缩包",CSV 是"通用文本表格"。
[解释] `np.save` 保存为 .npy 格式(单数组),`np.savez` 保存多个数组为 .npz,`np.load` 加载。`savetxt/loadtxt` 用于文本格式(CSV)。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 保存为 .npy 格式(单数组,二进制)
np.save("data.npy", a)

# 加载 .npy
b = np.load("data.npy")
print(b)

# 保存多个数组为 .npz 格式
np.savez("data.npz", x=a, y=a * 2)

# 加载 .npz
data = np.load("data.npz")
print(data["x"])      # 原数组
print(data["y"])      # 翻倍数组


# --- 执行过程 ---

① 第2行: 创建 2x3 矩阵 a

② 第5行: `np.save('data.npy', a)` 保存为 .npy 文件

② 第8行: `np.load('data.npy')` 加载,完全恢复原数组

③ 第11行: `np.savez('data.npz', x=a, y=a*2)` 保存多个数组

④ 第15行: 通过键名访问 npz 中的数组

**逐行解剖**

- `np.save(fname, arr)`:保存为 .npy 二进制格式
- `np.load(fname)`:加载 .npy 或 .npz
- `np.savez(fname, **kwargs)`:保存多个数组,用关键字参数命名
- .npy 保留 dtype 和 shape,CSV 不保留

**练习**

创建一个 3x3 随机矩阵,保存为 .npy 文件,再加载验证数据一致。

> 问自己:
> - 这道题要用到今天学的哪个知识点? (np.save / np.load)
> - 如果运行报错,检查什么? (文件路径是否正确)

In [ ]:
import numpy as np

# 学员代码区
pass


In [ ]:
import numpy as np

# 参考答案
np.random.seed(1)
mat = np.random.rand(3, 3)
np.save("my_matrix.npy", mat)
loaded = np.load("my_matrix.npy")
print(np.allclose(mat, loaded))  # True,数据一致


#### 文本格式 savetxt / loadtxt

[痛点] 需要与其他软件交换数据,.npy 格式不通用。
[类比] CSV 是"通用语言",Excel、R、MATLAB 都能读。
[解释] `np.savetxt` 保存为文本(CSV),`np.loadtxt` 加载文本。常用参数:`delimiter` 分隔符,`skiprows` 跳过行数,`header` 表头,`comments` 注释前缀。

In [ ]:
import numpy as np

# 创建数据
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

# 保存为 CSV,comments="" 去掉默认的 "#" 前缀
np.savetxt("output.csv", data, delimiter=",",
           header="col1,col2,col3", comments="")

# 加载 CSV,skiprows=1 跳过表头
loaded = np.loadtxt("output.csv", delimiter=",", skiprows=1)
print(loaded)


# --- 执行过程 ---

① 第2行: 创建 3x3 矩阵

② 第6行: `np.savetxt` 保存为 CSV,指定分隔符和表头

③ 第9行: `np.loadtxt` 加载,skiprows=1 跳过表头

**逐行解剖**

- `delimiter=","`:指定逗号分隔
- `header="col1,col2,col3"`:表头字符串
- `comments=""`:默认 header 前加 "# ",设为空字符串去掉
- `skiprows=1`:跳过第 1 行(表头),否则解析报错

**练习**

创建一个 4x2 矩阵,保存为 CSV 文件(用分号分隔),再加载验证。

> 问自己:
> - 这道题要用到今天学的哪个知识点? (savetxt / loadtxt)
> - 如果运行报错,检查什么? (delimiter 是否一致,skiprows 是否正确)

In [ ]:
import numpy as np

# 学员代码区
pass


In [ ]:
import numpy as np

# 参考答案
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
np.savetxt("semicolon.csv", data, delimiter=";",
           header="A,B", comments="")
loaded = np.loadtxt("semicolon.csv", delimiter=";", skiprows=1)
print(loaded)


**今日小结**

| 概念 | 解决的痛点 |
|------|------------|
| `*` vs `@` | 区分逐元素乘法和矩阵乘法 |
| `.T` / `det` / `inv` | 转置、行列式、逆矩阵 |
| `sum/mean/std/argmax` | 快速计算统计量 |
| `axis` 参数 | 按行或按列聚合 |
| `seed/normal/randint` | 可复现的随机数生成 |
| `save/load` | 二进制保存和加载数组 |
| `savetxt/loadtxt` | 文本格式(CSV)读写 |

**更多练习**

- 当堂练:course/lesson12/in_class/practice01-06.py
- 课后作业:course/lesson12/homework/task01-03.py